# As a general rule, favour the repos listed in the official
# pre-commit hooks page https://pre-commit.com/hooks.html

fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
#      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
#      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
#      - id: requirements-txt-fixer
#      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.2.1'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

#  - repo: https://github.com/psf/black-pre-commit-mirror
#    rev: 24.1.1
#    hooks:
#      - id: black
#        language_version: python3.11
