name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Hatch
        run: pip install hatch
      - name: Install dependencies
        run: hatch env create
      - name: Run pytest
        run: hatch run pytest test --verbose --durations=5
